fn_single_line = true
force_multiline_blocks = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
max_width = 100
match_arm_leading_pipes = "Always"
imports_granularity = "Module"
reorder_impl_items = true
group_imports = "StdExternalCrate"
reorder_modules = true
use_try_shorthand = true
wrap_comments = true